---
title: "Warmup_lab6"
output: 
  html_document: 
    keep_md: yes
date: "2024-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load tidyverse
```{r}
library(tidyverse)
```
## 1. load bison data
```{r}
getwd()
bison <- read_csv("data/bison.csv")
```
## 2. dimensions and structure of data.
```{r}
dim(bison)
```

```{r}
str(bison)
```

```{r}
bison
```
## 3. New data frame with code, sex, weight, and age
```{r}
new_bison <- select(bison, "data_code", "animal_sex", "animal_weight", "animal_yob")
new_bison
```
## 4. Restrict to year 1980 to 1990. 
```{r}
new_bison %>% 
  filter(between(animal_yob, 1980, 1990))
```
## 5. filter by sex
```{r}
female_bison <- new_bison %>% 
  filter(between(animal_yob, 1980, 1990)) %>% 
  filter(animal_sex=="F")
female_bison
```


```{r}
male_bison <- new_bison %>% 
  filter(between(animal_yob, 1980, 1990)) %>% 
  filter(animal_sex=="M")
male_bison
```

## how many males and females?
```{r}
dim(female_bison)
dim(male_bison)

table(male_bison$animal_sex)
```

## 6. Are males or females larger on average from 1980-1990?
```{r}
mean(female_bison$animal_weight)
```

```{r}
mean(male_bison$animal_weight)
```

## Males are larger on average from year 1980-1990. 
